export const GET_SHIPPING_METHODS = 'checkout/GET_SHIPPING_METHODS';
export const GET_SHIPPING_METHODS_SUCCESS =
  'checkout/GET_SHIPPING_METHODS_SUCCESS';
export const GET_SHIPPING_METHODS_ERROR = 'checkout/GET_SHIPPING_METHODS_ERROR';

export const CHANGE_CHOSEN_METHOD = 'checkout/CHANGE_CHOSEN_METHOD';
export const CHANGE_DIFFERENT_ADDRESS = 'checkout/CHANGE_DIFFERENT_ADDRESS';

export const UPDATE_ADDRESS = 'checkout/UPDATE_ADDRESS';
export const SELECT_PAYMENT_METHOD = 'checkout/SELECT_PAYMENT_METHOD';
export const CHANGE_CUSTOMER_NOTE = 'checkout/CHANGE_CUSTOMER_NOTE';

export const UPDATE_ORDER_REVIEW = 'checkout/UPDATE_ORDER_REVIEW';
export const UPDATE_ORDER_REVIEW_SUCCESS =
  'checkout/UPDATE_ORDER_REVIEW_SUCCESS';
export const UPDATE_ORDER_REVIEW_ERROR = 'checkout/UPDATE_ORDER_REVIEW_ERROR';

export const CHECKOUT = 'checkout/CHECKOUT';
export const CHECKOUT_SUCCESS = 'checkout/CHECKOUT_SUCCESS';
export const CHECKOUT_ERROR = 'checkout/CHECKOUT_METHODS_ERROR';
